"""add column fcm_token in the table user

Revision ID: 3ea8f6519a32
Revises: 4442c13e7323
Create Date: 2025-08-24 09:57:05.737792

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3ea8f6519a32'
down_revision: Union[str, None] = '4442c13e7323'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('fcm_token', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'fcm_token')
    # ### end Alembic commands ###
