"""Updating table debt

Revision ID: ac09c874a053
Revises: 5db04665c6d4
Create Date: 2025-02-10 12:39:31.266078

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ac09c874a053'
down_revision: Union[str, None] = '5db04665c6d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


from alembic import op
import sqlalchemy as sa

def upgrade():
    op.alter_column(
        'debt',
        'duedate',
        existing_type=sa.VARCHAR(),
        type_=sa.Date(),
        existing_nullable=False,
        postgresql_using="duedate::DATE"  # Aqui está a correção!
    )



def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('debt', 'duedate',
               existing_type=sa.Date(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    # ### end Alembic commands ###
