name: Pipeline
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      SECRET_KEY: ${{ secrets.SECRET_KEY }}
      ALGORITHM: ${{ secrets.ALGORITHM }}
      ACCESS_TOKEN_EXPIRE_MINUTES: ${{ secrets.ACCESS_TOKEN_EXPIRE_MINUTES }}
      FIREBASE_KEY: ${{ secrets.FIREBASE_KEY }}

    steps:
      - name: Copia os arquivos do repositório
        uses: actions/checkout@v3
        
      - name: Instalar o python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Instalar o poetry
        run: pipx install poetry

      - name: Instalar dependências
        run: poetry install

      - name: Criar arquivo firebase.json
        run: echo "$FIREBASE_KEY" > firebase.json

      - name: Executar testes
        run: poetry run task test
